# Generated by Django 3.2.8 on 2023-01-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230121_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionoptions',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='attachment',
            field=models.URLField(blank=True, null=True),
        ),
    ]
