# Generated by Django 3.2.8 on 2023-01-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230121_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptions',
            name='option_description',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_description',
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
