# Generated by Django 3.2.8 on 2023-01-22 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230122_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='questionoptions',
            name='for_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option', to='core.questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.image'),
        ),
    ]
