export enum BUSINESS_TYPES {
  PERSONAL = 'PERSONAL',
  FRANCHISES = 'FRANCHISES',
}

export enum BRAND_TYPES {
  SHOES = 'SHOES',
  WATCH = 'WATCH',
  MOBILE = 'MOBILE',
}

export enum PLANS {
  LAUNCH = 'LAUNCH',
  STANDARD = 'STANDARD',
  PREMIUM = 'PREMIUM',
  OTHER = 'OTHER',
}

export enum MERCHANT_STAFF_ROLES {
  STAFF = 'STAFF',
  MANAGER = 'MANAGER',
  OWNER = 'OWNER',
}

export enum KYS_VERIFICATION_STATUS {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum KYS_STEP {
  AADHAAR = 'AADHAAR',
  COLLEGE_EMAIL = 'COLLEGE_EMAIL',
  COLLEGE_ID_CARD = 'COLLEGE_ID_CARD',
  REGISTRATION_CERTIFICATE = 'REGISTRATION_CERTIFICATE',
  ADDITIONAL_DOCUMENT = 'ADDITIONAL_DOCUMENT',
  VIDEO = 'VIDEO',
}

export enum PAYMENT_METHODS {
  CASH = 'cash',
  UPI = 'upi',
  CARD = 'card',
}
